# Generated by Django 5.1.3 on 2024-11-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_crop_crop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='crop_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/crops/'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/farmers/'),
        ),
    ]
